spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  profiles: local
  datasource:
    data: 
        classpath:tech_data-h2.sql
      , classpath:news_data-h2.sql
      , classpath:main_menu_data-h2.sql
      , classpath:member_rankings_data-h2.sql
      , classpath:team_rankings_data-h2.sql
      , classpath:member_results_data-h2.sql
      , classpath:comments_data-h2.sql
      , classpath:members_data-h2.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
