insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (1,  1, 'LaPImpact', 999, 9, 9, 9, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (2,  2, 'xixvi'    , 888, 8, 8, 8, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (3,  3, 'Tzarrrr'  , 777, 7, 7, 7, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (4,  4, 'akbare'   , 666, 6, 6, 6, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (5,  5, 'yolmu'    , 555, 5, 5, 5, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (6,  6, 'Mikel'    , 444, 4, 4, 4, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (7,  7, 'DDang'    , 333, 3, 3, 3, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (8,  8, '050505'   , 222, 2, 2, 2, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (9,  9, 'Gom'      , 111, 1, 1, 1, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (10,10, 'lottoo'   , 000, 0, 0, 0, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (11,11, 'LaPImpact', 999, 9, 9, 9, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (12,12, 'xixvi'    , 888, 8, 8, 8, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (13,13, 'Tzarrrr'  , 777, 7, 7, 7, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (14,14, 'akbare'   , 666, 6, 6, 6, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (15,15, 'yolmu'    , 555, 5, 5, 5, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (16,16, 'Mikel'    , 444, 4, 4, 4, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (17,17, 'DDang'    , 333, 3, 3, 3, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (18,18, '050505'   , 222, 2, 2, 2, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (19,19, 'Gom'      , 111, 1, 1, 1, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (20,20, 'lottoo'   , 000, 0, 0, 0, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (20,20, 'lottoo'   , 000, 0, 0, 0, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (21,21, 'LaPImpact', 999, 9, 9, 9, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (22,22, 'xixvi'    , 888, 8, 8, 8, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (23,23, 'Tzarrrr'  , 777, 7, 7, 7, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (24,24, 'akbare'   , 666, 6, 6, 6, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (25,25, 'yolmu'    , 555, 5, 5, 5, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (26,26, 'Mikel'    , 444, 4, 4, 4, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (27,27, 'DDang'    , 333, 3, 3, 3, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (28,28, '050505'   , 222, 2, 2, 2, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (29,29, 'Gom'      , 111, 1, 1, 1, now(), now());
insert into member_rankings (ranking, member_id, name, rating, win, draw, lose, created_date, modified_date) values (30,30, 'lottoo'   , 000, 0, 0, 0, now(), now());

