insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (1, 'LaPImpact', 9999, 9, 9, 9, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (2, 'xixvi'    , 8888, 8, 8, 8, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (3, 'Tzarrrr'  , 7777, 7, 7, 7, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (4, 'akbare'   , 6666, 6, 6, 6, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (5, 'yolmu'    , 5555, 5, 5, 5, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (6, 'Mikel'    , 4444, 4, 4, 4, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (7, 'DDang'    , 3333, 3, 3, 3, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (8, '050505'   , 2222, 2, 2, 2, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (9, 'Gom'      , 1111, 1, 1, 1, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (10, 'lottoo'   , 0000, 0, 0, 0, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (11, 'LaPImpact', 9999, 9, 9, 9, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (12, 'xixvi'    , 8888, 8, 8, 8, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (13, 'Tzarrrr'  , 7777, 7, 7, 7, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (14, 'akbare'   , 6666, 6, 6, 6, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (15, 'yolmu'    , 5555, 5, 5, 5, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (16, 'Mikel'    , 4444, 4, 4, 4, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (17, 'DDang'    , 3333, 3, 3, 3, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (18, '050505'   , 2222, 2, 2, 2, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (19, 'Gom'      , 1111, 1, 1, 1, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (20, 'lottoo'   , 0000, 0, 0, 0, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (20, 'lottoo'   , 0000, 0, 0, 0, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (21, 'LaPImpact', 9999, 9, 9, 9, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (22, 'xixvi'    , 8888, 8, 8, 8, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (23, 'Tzarrrr'  , 7777, 7, 7, 7, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (24, 'akbare'   , 6666, 6, 6, 6, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (25, 'yolmu'    , 5555, 5, 5, 5, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (26, 'Mikel'    , 4444, 4, 4, 4, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (27, 'DDang'    , 3333, 3, 3, 3, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (28, '050505'   , 2222, 2, 2, 2, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (29, 'Gom'      , 1111, 1, 1, 1, now(), now());
insert into member_ranking (ranking, name, rating, win, draw, lose, created_date, modified_date) values (30, 'lottoo'   , 0000, 0, 0, 0, now(), now());

