insert into members (id, team_id, name, won, draw, lost, rating, winning_point, winning_rate, goal, goal_average, lost_goal, lost_goal_average, created_date, modified_date) values (1, 1, 'LaP',    9, 9, 9, 1122, 36, 33, 270, 10, 54, 2, now(), now());
insert into members (id, team_id, name, won, draw, lost, rating, winning_point, winning_rate, goal, goal_average, lost_goal, lost_goal_average, created_date, modified_date) values (2, 2, 'JuN',    8, 8, 8, 1600, 32, 33, 240, 10, 48, 2, now(), now());
insert into members (id, team_id, name, won, draw, lost, rating, winning_point, winning_rate, goal, goal_average, lost_goal, lost_goal_average, created_date, modified_date) values (3, 3, 'Nikel',  7, 7, 7, 1000, 28, 33, 210, 10, 42, 2, now(), now());
insert into members (id, team_id, name, won, draw, lost, rating, winning_point, winning_rate, goal, goal_average, lost_goal, lost_goal_average, created_date, modified_date) values (4, 4, 'Lottoo', 6, 6, 6, 3400, 24, 33, 180, 10, 36, 2, now(), now());
insert into members (id, team_id, name, won, draw, lost, rating, winning_point, winning_rate, goal, goal_average, lost_goal, lost_goal_average, created_date, modified_date) values (5, 5, 'aK',     5, 5, 5,  998, 20, 33, 150, 10, 30, 2, now(), now());
insert into members (id, team_id, name, won, draw, lost, rating, winning_point, winning_rate, goal, goal_average, lost_goal, lost_goal_average, created_date, modified_date) values (6, 6, 'Dang',   4, 4, 4, 1003, 16, 33, 120, 10, 24, 2, now(), now());
insert into members (id, team_id, name, won, draw, lost, rating, winning_point, winning_rate, goal, goal_average, lost_goal, lost_goal_average, created_date, modified_date) values (7, 7, 'Tzarr',  3, 3, 3, 1120, 12, 33, 90,  10, 18, 2, now(), now());
insert into members (id, team_id, name, won, draw, lost, rating, winning_point, winning_rate, goal, goal_average, lost_goal, lost_goal_average, created_date, modified_date) values (8, 8, 'XiviX',  2, 2, 2,  800, 8,  33, 60,  10, 12, 2, now(), now());
insert into members (id, team_id, name, won, draw, lost, rating, winning_point, winning_rate, goal, goal_average, lost_goal, lost_goal_average, created_date, modified_date) values (9, 9, '050505', 1, 1, 1,  920, 4,  33, 30,  10, 6,  2, now(), now());
insert into members (id, team_id, name, won, draw, lost, rating, winning_point, winning_rate, goal, goal_average, lost_goal, lost_goal_average, created_date, modified_date) values (10,10,'Gom',    0, 0, 0,    0, 0,   0,  0,   0, 0,  0, now(), now());

